### ISSUE TITLE
recordio.Reader should be independent with the concept of chunk

### ISSUE THREAD

**Issue by wangkuiyi** [elasticdl/pyrecordio#23]
Currently 

https://github.com/ElasticDL/pyrecordio/blob/develop/recordio/recordio/reader.py#L6

However, chunk is a concept must be hidden from the end-users. `recordio.Reader` should provide an interface of reading a range of records, instead of chunks.

**Comment by wangkuiyi** [comment]
What we want is something like the following:

```python
import recordio

with open('demo.recordio', 'rb') as fp:
    idx = recordio.FileIndex(fp)
    print('Total file records: ' + str(idx.total_records()))

    for i in range(10):  # to split the records into 10 partitions.
        r = recordio.RangeReader(fp,
                                 i*idx.total_records()/10,
                                 (i+1)*idx.total_records()/10)
        print('Total chunk records: ' + str(r.total_count()))

        while r.has_next():
            print('record value: ' + r.next())
```

This design comes from my original Go implementation of [`RangeScanner`](https://github.com/PaddlePaddle/recordio/blob/1a278fc674c28783aa5925610bac9dfb745711e0/recordio_test.go#L68-L87). It happens to be similar to Alibaba ODPS's [`partition.Reader`](https://pyodps.readthedocs.io/en/latest/api-def.html#odps.models.partition.Partition.open_reader):

```python
with partition.open_reader() as reader:
    count = reader.count  # How many records of a partition
    for record in reader[0: count]:
        # read all data, actually better to split into reading for many times
```

**Comment by zou000** [comment]
我先做一下，等 @yuyicg 醒了 review。
